config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    get 'about', to: 'pages#about'
    get 'explore', to: 'pages#explore'
    resources :contacts
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  
  def about
  end
  
  def explore
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <div class="contact-form">
      <h3 class="text-center">Contact Us</h3>
    </div>
      <div class="col-md-4 col-md-offset-4">
        <div class="well">
          
          <%= form_for "/contacts" do |f| %>
          
           <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: 'form-control' %>
            </div>
            
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: 'form-control'%>
            </div>
            
            <div class="form-group">
              <%= f.label :comments %>
              <%= f.text_area :comments, class: 'form-control' %>
            </div>
            
            <%= f.submit 'Submit',class: 'btn btn-primary' %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
     <link href="//fonts.googleapis.com/css?family=Oswald:400,600,700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
  <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      <i class="fab fa-deskpro"></i> 
      <link href="https://fonts.googleapis.com/css?family=Audiowide|Gloria+Hallelujah&display=swap" rel="stylesheet">
      Farmiza 
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Explore', explore_path %></li>
        <li><%= link_to 'Contact Us', new_contact_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-us container-fluid text-center">
  <h1>About Page</h1>
  <p>We are farmizans.<br>
    We Supply the premium quality dairy products to fulfill your priceless needs.
  </p>
</div>

app/views/pages/explore.html.erb
<div class=" explore-more container-fluid text-center">
  <h1>Explore more about our page here.</h1>
  <p>Explore more about us by visiting our farm house and by being in touch of this site</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1> Welcome to e-dairy</h1>
  <h3>A new way to buy dairy products</h3>
</div>